CREATE TABLE IF NOT EXISTS db.brands
(
    id         BIGINT AUTO_INCREMENT  NOT NULL,
    name       VARCHAR(255)           NULL,
    slug       VARCHAR(255)           NULL,
    `order`    INT(11) DEFAULT 1,
    image_url  VARCHAR(255)           NULL,
    seo_title  VARCHAR(255)           NULL,
    section_id BIGINT                 NULL,
    created_at datetime DEFAULT NOW(),
    updated_at datetime DEFAULT NOW() ON UPDATE NOW(),
    CONSTRAINT pk_brands PRIMARY KEY (id)
);

ALTER TABLE db.brands
    ADD CONSTRAINT FK_BRANDS_ON_SECTION FOREIGN KEY (section_id) REFERENCES db.sections (id);

INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (1, 'Acura', 'acura', '1', 1, 'acura'),
       (2, 'Aixam', 'Aixam', '2', 1, 'Aixam'),
       (3, 'Alfa Romeo', 'Alfa Romeo', '3', 1, 'Alfa Romeo'),
       (4, 'Alpina', 'Alpina', '4', 1, 'Alpina'),
       (5, 'Asia Motors', 'asia motors', '5', 1, 'asia motors'),
       (6, 'Aston Martin', 'Aston Martin', '6', 1, 'Aston Martin'),
       (7, 'Audi', 'Audi', '7', 1, 'Audi'),
       (8, 'Austin', 'austin', '8', 1, 'austin'),
       (9, 'Bentley', 'Bentley', '1', 1, 'Bentley'),
       (10, 'BMW', 'BMW', '2', 1, 'BMW');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (11, 'Brilliance', 'Brilliance', '3', 1, 'Brilliance'),
       (12, 'Buick', 'Buick', '4', 1, 'Buick'),
       (13, 'Cadillac', 'Cadillac', '1', 1, 'Cadillac'),
       (14, 'Chevrolet', 'Chevrolet', '2', 1, 'Chevrolet'),
       (15, 'Chrysler', 'Chrysler', '3', 1, 'Chrysler'),
       (16, 'Bugatti', 'Bugatti', '5', 1, 'Bugatti'),
       (17, 'Citroen', 'Citroen', '4', 1, 'Citroen'),
       (18, 'Corvette', 'Corvette', '5', 1, 'Corvette'),
       (19, 'Dacia', 'Dacia', '1', 1, 'Dacia'),
       (20, 'Daewoo', 'Daewoo', '2', 1, 'Daewoo');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (21, 'Daihatsu', 'Daihatsu', '3', 1, 'Daihatsu'),
       (22, 'Datsun', 'Datsun', '4', 1, 'Datsun'),
       (23, 'Dodge', 'Dodge', '5', 1, 'Dodge'),
       (24, 'DR', 'DR', '6', 1, 'DR'),
       (25, 'Ferrari', 'Ferrari', '1', 1, 'Ferrari'),
       (26, 'Fiat', 'Fiat', '2', 1, 'Fiat'),
       (27, 'Ford', 'Ford', '3', 1, 'Ford'),
       (28, 'Gac Gonow', 'Gac Gonow', '1', 1, 'Gac Gonow'),
       (29, 'GAZ', 'GAZ', '2', 1, 'GAZ'),
       (30, 'GMC', 'GMC', '3', 1, 'GMC');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (31, 'Great wall', 'Great wall', '4', 1, 'Great wall'),
       (32, 'Honda', 'Honda', '1', 1, 'Honda'),
       (33, 'Hummer', 'Hummer', '2', 1, 'Hummer'),
       (34, 'Hyundai', 'Hyundai', '3', 1, 'Hyundai'),
       (35, 'Infiniti', 'Infiniti', '1', 1, 'Infiniti'),
       (36, 'Isuzu', 'Isuzu', '2', 1, 'Isuzu'),
       (37, 'Iveco', 'Iveco', '3', 1, 'Iveco'),
       (38, 'Jaguar', 'Jaguar', '1', 1, 'Jaguar'),
       (39, 'Jeep', 'Jeep', '2', 1, 'Jeep'),
       (40, 'Kia', 'Kia', '1', 1, 'Kia');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (41, 'Lada', 'Lada', '1', 1, 'Lada'),
       (42, 'Lamborghini', 'Lamborghini', '2', 1, 'Lamborghini'),
       (43, 'Lancia', 'Lancia', '3', 1, 'Lancia'),
       (44, 'Land Rover', 'Land Rover', '4', 1, 'Land Rover'),
       (45, 'Lexus', 'Lexus', '4', 1, 'Lexus'),
       (46, 'Lincoln', 'Lincoln', '5', 1, 'Lincoln'),
       (47, 'Lotus', 'Lotus', '6', 1, 'Lotus'),
       (48, 'Mahindra', 'Mahindra', '1', 1, 'Mahindra'),
       (49, 'Maserati', 'Maserati', '2', 1, 'Maserati'),
       (50, 'Maybach', 'Maybach', '3', 1, 'Maybach');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (51, 'Mazda', 'Mazda', '4', 1, 'Mazda'),
       (52, 'McLaren', 'McLaren', '5', 1, 'McLaren'),
       (53, 'Mercedes-Benz', 'Mercedes-Benz', '6', 1, 'Mercedes-Benz'),
       (54, 'MG', 'MG', '7', 1, 'MG'),
       (55, 'Mini', 'Mini', '8', 1, 'Mini'),
       (56, 'Mitsubishi', 'Mitsubishi', '9', 1, 'Mitsubishi'),
       (57, 'Moskvich', 'Moskvich', '10', 1, 'Moskvich'),
       (58, 'Nissan', 'Nissan', '1', 1, 'Nissan'),
       (59, 'Oldsmobile', 'Oldsmobile', '1', 1, 'Oldsmobile'),
       (60, 'Opel', 'Opel', '2', 1, 'Opel');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (61, 'Peugeot', 'Peugeot', '1', 1, 'Peugeot'),
       (62, 'Piaggio', 'Piaggio', '2', 1, 'Piaggio'),
       (63, 'Pontiac', 'Pontiac', '3', 1, 'Pontiac'),
       (64, 'Porsche', 'Porsche', '4', 1, 'Porsche'),
       (65, 'Range Rover', 'Range Rover', '1', 1, 'Range Rover'),
       (66, 'Renault', 'Renault', '2', 1, 'Renault'),
       (67, 'Rolls Royce', 'Rolls Royce', '3', 1, 'Rolls Royce'),
       (68, 'Rover', 'Rover', '4', 1, 'Rover'),
       (69, 'Saab', 'Saab', '1', 1, 'Saab'),
       (70, 'Scion', 'Scion', '2', 1, 'Scion');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (71, 'Seat', 'Seat', '3', 1, 'Seat'),
       (72, 'Shuanghuan', 'Shuanghuan', '4', 1, 'Shuanghuan'),
       (73, 'Skoda', 'Skoda', '5', 1, 'Skoda'),
       (74, 'Smart', 'Smart', '6', 1, 'Smart'),
       (75, 'Ssangyong', 'Ssangyong', '7', 1, 'Ssangyong'),
       (76, 'STOEWER', 'STOEWER', '8', 1, 'STOEWER'),
       (77, 'Subaru', 'Subaru', '9', 1, 'Subaru'),
       (78, 'Suzuki', 'Suzuki', '10', 1, 'Suzuki'),
       (79, 'Talbot', 'Talbot', '1', 1, 'Talbot'),
       (80, 'Tata', 'Tata', '2', 1, 'Tata');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (81, 'Tesla', 'Tesla', '3', 1, 'Tesla'),
       (82, 'Toyota', 'Toyota', '4', 1, 'Toyota'),
       (83, 'Trabant', 'Trabant', '5', 1, 'Trabant'),
       (84, 'UAZ', 'UAZ', '1', 1, 'UAZ'),
       (85, 'Volga', 'Volga', '1', 1, 'Volga'),
       (86, 'Volvo', 'Volvo', '2', 1, 'Volvo'),
       (87, 'VW', 'VW', '3', 1, 'VW'),
       (88, 'Wartburg', 'Wartburg', '1', 1, 'Wartburg'),
       (89, 'Yogomo', 'Yogomo', '1', 1, 'Yogomo'),
       (90, 'Zastava', 'Zastava', '1', 1, 'Zastava');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (91, 'Zaz', 'Zaz', '2', 1, 'Zaz'),
       (92, 'ВАЗ', 'ВАЗ', '1', 1, 'ВАЗ'),
       (93, 'Варшава', 'Варшава', '2', 1, 'Варшава'),
       (94, 'Avia', 'Avia', '1', 2, 'Avia'),
       (95, 'Ayats', 'Ayats', '2', 2, 'Ayats'),
       (96, 'Barkas', 'Barkas', '1', 2, 'Barkas'),
       (97, 'Bedford', 'Bedford', '2', 2, 'Bedford'),
       (98, 'Blue Bird', 'Blue Bird', '3', 2, 'Blue Bird'),
       (99, 'Bova', 'Bova', '4', 2, 'Bova'),
       (100, 'Brilliance', 'Brilliance', '5', 2, 'Brilliance');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (101, 'Chavdar', 'Chavdar', '1', 2, 'Chavdar'),
       (102, 'Chevrolet', 'Chevrolet', '2', 2, 'Chevrolet'),
       (103, 'Citroen', 'Citroen', '3', 2, 'Citroen'),
       (104, 'Cobra', 'Cobra', '4', 2, 'Cobra'),
       (105, 'DFSK', 'DFSK', '1', 2, 'DFSK'),
       (106, 'Daewoo', 'Daewoo', '2', 2, 'Daewoo'),
       (107, 'Daf', 'Daf', '3', 2, 'Daf'),
       (108, 'Daihatsu', 'Daihatsu', '4', 2, 'Daihatsu'),
       (109, 'Dodge', 'Dodge', '5', 2, 'Dodge'),
       (110, 'Drogmoller', 'Drogmoller', '6', 2, 'Drogmoller');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (111, 'Fiat', 'Fiat', '1', 2, 'Fiat'),
       (112, 'Ford', 'Ford', '2', 2, 'Ford'),
       (113, 'Gaz', 'Gaz', '1', 2, 'Gaz'),
       (114, 'Gazela', 'Gazela', '2', 2, 'Gazela'),
       (115, 'Gmc', 'Gmc', '3', 2, 'Gmc'),
       (116, 'Harmony', 'Harmony', '1', 2, 'Harmony'),
       (117, 'Hyundai', 'Hyundai', '2', 2, 'Hyundai'),
       (118, 'Ikarus', 'Ikarus', '1', 2, 'Ikarus'),
       (119, 'Isuzu', 'Isuzu', '2', 2, 'Isuzu'),
       (120, 'Iveco', 'Iveco', '3', 2, 'Iveco');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (121, 'Jonckheere', 'Jonckheere', '1', 2, 'Jonckheere'),
       (122, 'Karosa', 'Karosa', '1', 2, 'Karosa'),
       (123, 'Kia', 'Kia', '2', 2, 'Kia'),
       (124, 'King Long', 'King Long', '3', 2, 'King Long'),
       (125, 'LDV', 'LDV', '1', 2, 'LDV'),
       (126, 'Lancia', 'Lancia', '2', 2, 'Lancia'),
       (127, 'Latvia', 'Latvia', '3', 2, 'Latvia'),
       (128, 'Lifan', 'Lifan', '4', 2, 'Lifan'),
       (129, 'Luaz', 'Luaz', '5', 2, 'Luaz'),
       (130, 'Man', 'Man', '1', 2, 'Man');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (131, 'Marcopolo', 'Marcopolo', '2', 2, 'Marcopolo'),
       (132, 'Matra', 'Matra', '3', 2, 'Matra'),
       (133, 'Mazda', 'Mazda', '4', 2, 'Mazda'),
       (134, 'Mercedes-Benz', 'Mercedes-Benz', '6', 2, 'Mercedes-Benz'),
       (135, 'Mitsubishi', 'Mitsubishi', '7', 2, 'Mitsubishi'),
       (136, 'Neoplan', 'Neoplan', '1', 2, 'Neoplan'),
       (137, 'Nisa', 'Nisa', '2', 2, 'Nisa'),
       (138, 'Nissan', 'Nissan', '3', 2, 'Nissan'),
       (139, 'Opel', 'Opel', '1', 2, 'Opel'),
       (140, 'Otokar', 'Otokar', '2', 2, 'Otokar');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (141, 'Paz', 'Paz', '1', 2, 'Paz'),
       (142, 'Peugeot', 'Peugeot', '2', 2, 'Peugeot'),
       (143, 'Piaggio', 'Piaggio', '3', 2, 'Piaggio'),
       (144, 'Plimouth', 'Plimouth', '4', 2, 'Plimouth'),
       (145, 'Pontiac', 'Pontiac', '5', 2, 'Pontiac'),
       (146, 'Raf', 'Raf', '1', 2, 'Raf'),
       (147, 'Renault', 'Renault', '2', 2, 'Renault'),
       (148, 'Robur', 'Robur', '3', 2, 'Robur'),
       (149, 'Rocar', 'Rocar', '4', 2, 'Rocar'),
       (150, 'Rover', 'Rover', '5', 2, 'Rover');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (151, 'Sanos', 'Sanos', '1', 2, 'Sanos'),
       (152, 'Scania', 'Scania', '2', 2, 'Scania'),
       (153, 'Setra', 'Setra', '3', 2, 'Setra'),
       (154, 'Shayer', 'Shayer', '4', 2, 'Shayer'),
       (155, 'Skoda', 'Skoda', '5', 2, 'Skoda'),
       (156, 'Smit', 'Smit', '6', 2, 'Smit'),
       (157, 'Steyr', 'Steyr', '7', 2, 'Steyr'),
       (158, 'Subaru', 'Subaru', '8', 2, 'Subaru'),
       (159, 'Suzuki', 'Suzuki', '9', 2, 'Suzuki'),
       (160, 'Temsa', 'Temsa', '1', 2, 'Temsa');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (161, 'Toyota', 'Toyota', '2', 2, 'Toyota'),
       (162, 'Uaz', 'Uaz', '1', 2, 'Uaz'),
       (163, 'VW', 'VW', '1', 2, 'VW'),
       (164, 'Vanhool', 'Vanhool', '2', 2, 'Vanhool'),
       (165, 'Vdl Berkhof', 'Vdl Berkhof', '3', 2, 'Vdl Berkhof'),
       (166, 'Vdl Bova', 'Vdl Bova', '4', 2, 'Vdl Bova'),
       (167, 'Vdl Joncheere', 'Vdl Joncheere', '5', 2, 'Vdl Joncheere'),
       (168, 'Volvo', 'Volvo', '6', 2, 'Volvo'),
       (169, 'Zuk', 'Zuk', '1', 2, 'Zuk'),
       (170, 'Avia', 'Avia', '1', 5, 'Avia');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (171, 'Barkas', 'Barkas', '1', 5, 'Barkas'),
       (172, 'Berna', 'Berna', '2', 5, 'Berna'),
       (173, 'Bmc', 'Bmc', '3', 5, 'Bmc'),
       (174, 'Bocheng', 'Bocheng', '4', 5, 'Bocheng'),
       (175, 'Bremach', 'Bremach', '5', 5, 'Bremach'),
       (176, 'Bucher', 'Bucher', '6', 5, 'Bucher'),
       (177, 'Citroen', 'Citroen', '1', 5, 'Citroen'),
       (178, 'Daewoo', 'Daewoo', '1', 5, 'Daewoo'),
       (179, 'Daf', 'Daf', '2', 5, 'Daf'),
       (180, 'Daimler', 'Daimler', '3', 5, 'Daimler');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (181, 'Dennis', 'Dennis', '4', 5, 'Dennis'),
       (182, 'Dodge', 'Dodge', '5', 5, 'Dodge'),
       (183, 'Eagle', 'Eagle', '1', 5, 'Eagle'),
       (184, 'Erf', 'Erf', '2', 5, 'Erf'),
       (185, 'Fabela', 'Fabela', '1', 5, 'Fabela'),
       (186, 'Faun', 'Faun', '2', 5, 'Faun'),
       (187, 'Fedra', 'Fedra', '3', 5, 'Fedra'),
       (188, 'Fiat', 'Fiat', '4', 5, 'Fiat'),
       (189, 'Foden', 'Foden', '5', 5, 'Foden'),
       (190, 'Ford', 'Ford', '6', 5, 'Ford');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (191, 'Gaz', 'Gaz', '1', 5, 'Gaz'),
       (192, 'Gazela', 'Gazela', '2', 5, 'Gazela'),
       (193, 'Ginaf', 'Ginaf', '3', 5, 'Ginaf'),
       (194, 'Hanomag', 'Hanomag', '1', 5, 'Hanomag'),
       (195, 'Henshel', 'Henshel', '2', 5, 'Henshel'),
       (196, 'Hino', 'Hino', '3', 5, 'Hino'),
       (197, 'Hyundai', 'Hyundai', '4', 5, 'Hyundai'),
       (198, 'Ielch', 'Ielch', '1', 5, 'Ielch'),
       (199, 'Ifa', 'Ifa', '2', 5, 'Ifa'),
       (200, 'Ikarus', 'Ikarus', '3', 5, 'Ikarus');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (201, 'Inter', 'Inter', '4', 5, 'Inter'),
       (202, 'International', 'International', '5', 5, 'International'),
       (203, 'Isuzu', 'Isuzu', '6', 5, 'Isuzu'),
       (204, 'Iveco', 'Iveco', '7', 5, 'Iveco'),
       (205, 'Johnston', 'Johnston', '1', 5, 'Johnston'),
       (206, 'Jum', 'Jum', '2', 5, 'Jum'),
       (207, 'Jumbo', 'Jumbo', '3', 5, 'Jumbo'),
       (208, 'Kamaz', 'Kamaz', '1', 5, 'Kamaz'),
       (209, 'Kia', 'Kia', '2', 5, 'Kia'),
       (210, 'Kraz', 'Kraz', '3', 5, 'Kraz');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (211, 'Ladog', 'Ladog', '1', 5, 'Ladog'),
       (212, 'Latvia', 'Latvia', '2', 5, 'Latvia'),
       (213, 'Leiland', 'Leiland', '3', 5, 'Leiland'),
       (214, 'Liaz', 'Liaz', '4', 5, 'Liaz'),
       (215, 'Lt', 'Lt', '5', 5, 'Lt'),
       (216, 'Luaz', 'Luaz', '6', 5, 'Luaz'),
       (217, 'Mack', 'Mack', '1', 5, 'Mack'),
       (218, 'Madara', 'Madara', '2', 5, 'Madara'),
       (219, 'Magerus', 'Magerus', '3', 5, 'Magerus'),
       (220, 'Man', 'Man', '4', 5, 'Man');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (221, 'Man-vw', 'Man-vw', '5', 5, 'Man-vw'),
       (222, 'Maz', 'Maz', '6', 5, 'Maz'),
       (223, 'Mazda', 'Mazda', '7', 5, 'Mazda'),
       (224, 'Mega', 'Mega', '8', 5, 'Mega'),
       (225, 'Mercedes-Benz', 'Mercedes-Benz', '9', 5, 'Mercedes-Benz'),
       (226, 'Mini', 'Mini', '10', 5, 'Mini'),
       (227, 'Mitsubishi', 'Mitsubishi', '11', 5, 'Mitsubishi'),
       (228, 'Mudan', 'Mudan', '12', 5, 'Mudan'),
       (229, 'Nisa', 'Nisa', '1', 5, 'Nisa'),
       (230, 'Nissan', 'Nissan', '2', 5, 'Nissan');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (231, 'Nova', 'Nova', '3', 5, 'Nova'),
       (232, 'Om', 'Om', '1', 5, 'Om'),
       (233, 'Opel', 'Opel', '2', 5, 'Opel'),
       (234, 'Peuegeot', 'Peuegeot', '1', 5, 'Peuegeot'),
       (235, 'Praga', 'Praga', '2', 5, 'Praga'),
       (236, 'Preslav', 'Preslav', '3', 5, 'Preslav'),
       (237, 'Raba', 'Raba', '1', 5, 'Raba'),
       (238, 'Renault', 'Renault', '2', 5, 'Renault'),
       (239, 'Robur', 'Robur', '3', 5, 'Robur'),
       (240, 'Roman', 'Roman', '4', 5, 'Roman');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (241, 'Rover', 'Rover', '5', 5, 'Rover'),
       (242, 'Scania', 'Scania', '1', 5, 'Scania'),
       (243, 'Seat', 'Seat', '2', 5, 'Seat'),
       (244, 'Seres', 'Seres', '3', 5, 'Seres'),
       (245, 'Setra', 'Setra', '4', 5, 'Setra'),
       (246, 'Sinotruk', 'Sinotruk', '5', 5, 'Sinotruk'),
       (247, 'Sisu', 'Sisu', '6', 5, 'Sisu'),
       (248, 'Skoda', 'Skoda', '7', 5, 'Skoda'),
       (249, 'Steyr', 'Steyr', '8', 5, 'Steyr'),
       (250, 'Tetra', 'Tetra', '1', 5, 'Tetra');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (251, 'Terberg', 'Terberg', '2', 5, 'Terberg'),
       (252, 'Toyota', 'Toyota', '3', 5, 'Toyota'),
       (253, 'Trail', 'Trail', '4', 5, 'Trail'),
       (254, 'Uaz', 'Uaz', '1', 5, 'Uaz'),
       (255, 'Ural', 'Ural', '2', 5, 'Ural'),
       (256, 'VW', 'VW', '1', 5, 'VW'),
       (257, 'Vanhool', 'Vanhool', '2', 5, 'Vanhool'),
       (258, 'Volvo', 'Volvo', '3', 5, 'Volvo'),
       (259, 'Yalcin Dorse', 'Yalcin Dorse', '1', 5, 'Yalcin Dorse'),
       (260, 'Yamo', 'Yamo', '2', 5, 'Yamo');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (261, 'Zastava', 'Zastava', '1', 5, 'Zastava'),
       (262, 'Zil', 'Zil', '2', 5, 'Zil'),
       (263, 'Камаз', 'Камаз', '1', 5, 'Камаз'),
       (264, 'Aeon', 'aeon', '1', 3, 'Aeon'),
       (265, 'American Ironhorse', 'American Ironhorse', '2', 3, 'American Ironhorse'),
       (266, 'Aprilia', 'Aprilia', '3', 3, 'Aprilia'),
       (267, 'Arctic Cat', 'Arctic Cat', '4', 3, 'Arctic Cat'),
       (268, 'Argo', 'Argo', '5', 3, 'Argo'),
       (269, 'ABI', 'ABI', '1', 4, 'ABI'),
       (270, 'Atala', 'Atala', '6', 3, 'Atala');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (271, 'Awo', 'Awo', '7', 3, 'Awo'),
       (272, 'BMW', 'BMW', '1', 3, 'BMW'),
       (273, 'BRP', 'BRP', '2', 3, 'BRP'),
       (274, 'Babetta', 'Babetta', '3', 3, 'Babetta'),
       (275, 'Balkan', 'Balkan', '4', 3, 'Balkan'),
       (276, 'Baotian', 'Baotian', '5', 3, 'Baotian'),
       (277, 'Bashan', 'Bashan', '6', 3, 'Bashan'),
       (278, 'Bemi', 'Bemi', '7', 3, 'Bemi'),
       (279, 'Benelli', 'Benelli', '8', 3, 'Benelli'),
       (280, 'Benzhou', 'Benzhou', '9', 3, 'Benzhou');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (281, 'Beta', 'Beta', '10', 3, 'Beta'),
       (282, 'Bombardier', 'Bombardier', '11', 3, 'Bombardier'),
       (283, 'Buell', 'Buell', '12', 3, 'Buell'),
       (284, 'Buyang', 'Buyang', '13', 3, 'Buyang'),
       (285, 'Gagiva', 'Gagiva', '1', 3, 'Gagiva'),
       (286, 'Can-Am', 'Can-Am', '2', 3, 'Can-Am'),
       (287, 'Cfmoto', 'Cfmoto', '3', 3, 'Cfmoto'),
       (288, 'Cpi', 'Cpi', '4', 3, 'Cpi'),
       (289, 'Cz', 'Cz', '5', 3, 'Cz'),
       (290, 'Dealim', 'Dealim', '1', 3, 'Dealim');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (291, 'Daytona', 'Daytona', '2', 3, 'Daytona'),
       (292, 'Derbi', 'Derbi', '3', 3, 'Derbi'),
       (293, 'Dkw', 'Dkw', '4', 3, 'Dkw'),
       (294, 'Ducati', 'Ducati', '5', 3, 'Ducati'),
       (295, 'Egl', 'Egl', '1', 3, 'Egl'),
       (296, 'Etz', 'Etz', '2', 3, 'Etz'),
       (297, 'Falcon', 'Falcon', '1', 3, 'Falcon'),
       (298, 'Fantic', 'Fantic', '2', 3, 'Fantic'),
       (299, 'Fym', 'Fym', '3', 3, 'Fym'),
       (300, 'Garelli', 'Garelli', '1', 3, 'Garelli');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (301, 'Gas Gas', 'Gas Gas', '2', 3, 'Gas Gas'),
       (302, 'Genata', 'Genata', '3', 3, 'Genata'),
       (303, 'Generic', 'Generic', '4', 3, 'Generic'),
       (304, 'Geo Ming', 'Geo Ming', '5', 3, 'Geo Ming'),
       (305, 'Gilera', 'Gilera', '6', 3, 'Gilera'),
       (306, 'Go-ped', 'Go-ped', '7', 3, 'Go-ped'),
       (307, 'HISUN', 'HISUN', '1', 3, 'HISUN'),
       (308, 'Harley- Devidson', 'Harley- Devidson', '2', 3, 'Harley- Devidson'),
       (309, 'Herkules', 'Herkules', '3', 3, 'Herkules'),
       (310, 'Honda', 'Honda', '4', 3, 'Honda');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (311, 'Husaberg', 'Husaberg', '5', 3, 'Husaberg'),
       (312, 'Husqvarna', 'Husqvarna', '6', 3, 'Husqvarna'),
       (313, 'Hyosung', 'Hyosung', '7', 3, 'Hyosung'),
       (314, 'Indian', 'Indian', '1', 3, 'Indian'),
       (315, 'Italjet', 'Italjet', '2', 3, 'Italjet'),
       (316, 'Jawa', 'Jawa', '1', 3, 'Jawa'),
       (317, 'Jianshe', 'Jianshe', '2', 3, 'Jianshe'),
       (318, 'Jinlun', 'Jinlun', '3', 3, 'Jinlun'),
       (319, 'Jocsport', 'Jocsport', '4', 3, 'Jocsport'),
       (320, 'Jonway', 'Jonway', '5', 3, 'Jonway');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (321, 'Kaisar', 'Kaisar', '1', 3, 'Kaisar'),
       (322, 'Kawasaki', 'Kawasaki', '2', 3, 'Kawasaki'),
       (323, 'Keeway', 'Keeway', '3', 3, 'Keeway'),
       (324, 'Kinetic', 'Kinetic', '4', 3, 'Kinetic'),
       (325, 'Kioti', 'Kioti', '5', 3, 'Kioti'),
       (326, 'Ktm', 'Ktm', '6', 3, 'Ktm'),
       (327, 'Kymco', 'Kymco', '7', 3, 'Kymco'),
       (328, 'Laverda', 'Laverda', '1', 3, 'Laverda'),
       (329, 'Lifan', 'Lifan', '2', 3, 'Lifan'),
       (330, 'Linhai', 'Linhai', '3', 3, 'Linhai');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (331, 'MV Agusta', 'MV Agusta', '1', 3, 'MV Agusta'),
       (332, 'Malaguti', 'Malaguti', '2', 3, 'Malaguti'),
       (333, 'Mbk', 'Mbk', '3', 3, 'Mbk'),
       (334, 'Mikilon', 'Mikilon', '4', 3, 'Mikilon'),
       (335, 'Moto Guzzi', 'Moto Guzzi', '5', 3, 'Moto Guzzi'),
       (336, 'Moto Morini', 'Moto Morini', '6', 3, 'Moto Morini'),
       (337, 'MotorHispania', 'MotorHispania', '7', 3, 'MotorHispania'),
       (338, 'Mz', 'Mz', '8', 3, 'Mz'),
       (339, 'Nsu', 'Nsu', '1', 3, 'Nsu'),
       (340, 'Pannonia', 'Pannonia', '1', 3, 'Pannonia');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (341, 'Peugeot', 'Peugeot', '2', 3, 'Peugeot'),
       (342, 'Piaggio', 'Piaggio', '3', 3, 'Piaggio'),
       (343, 'Pioneer Nevada', 'Pioneer Nevada', '4', 3, 'Pioneer Nevada'),
       (344, 'Pocketbike', 'Pocketbike', '5', 3, 'Pocketbike'),
       (345, 'Polaris', 'Polaris', '6', 3, 'Polaris'),
       (346, 'Puch', 'Puch', '7', 3, 'Puch'),
       (347, 'Qingqi', 'Qingqi', '1', 3, 'Qingqi'),
       (348, 'Rewaco', 'Rewaco', '1', 3, 'Rewaco'),
       (349, 'Rieju', 'Rieju', '2', 3, 'Rieju'),
       (350, 'Romet', 'Romet', '3', 3, 'Romet');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (351, 'Sachs', 'Sachs', '1', 3, 'Sachs'),
       (352, 'Sampo', 'Sampo', '2', 3, 'Sampo'),
       (353, 'Samyang', 'Samyang', '3', 3, 'Samyang'),
       (354, 'Scoot', 'Scoot', '4', 3, 'Scoot'),
       (355, 'Shineray', 'Shineray', '5', 3, 'Shineray'),
       (356, 'Simson', 'Simson', '6', 3, 'Simson'),
       (357, 'Ski- Doo', 'Ski- Doo', '7', 3, 'Ski- Doo'),
       (358, 'Sundiro', 'Sundiro', '8', 3, 'Sundiro'),
       (359, 'Sumsto', 'Sumsto', '9', 3, 'Sumsto'),
       (360, 'Suzuki', 'Suzuki', '10', 3, 'Suzuki');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (361, 'Swm', 'Swm', '11', 3, 'Swm'),
       (362, 'Sym', 'Sym', '12', 3, 'Sym'),
       (363, 'UGBEST', 'UGBEST', '1', 3, 'UGBEST'),
       (364, 'VROMOS', 'VROMOS', '1', 3, 'VROMOS'),
       (365, 'Vanetti', 'Vanetti', '2', 3, 'Vanetti'),
       (366, 'Vespa', 'Vespa', '3', 3, 'Vespa'),
       (367, 'Victory', 'Victory', '4', 3, 'Victory'),
       (368, 'Wangye', 'Wangye', '1', 3, 'Wangye'),
       (369, 'Wonsim', 'Wonsim', '2', 3, 'Wonsim'),
       (370, 'WT', 'WT', '3', 3, 'WT');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (371, 'Wuxi', 'Wuxi', '4', 3, 'Wuxi'),
       (372, 'Xingyu', 'Xingyu', '1', 3, 'Xingyu'),
       (373, 'Xingyue', 'Xingyue', '2', 3, 'Xingyue'),
       (374, 'Xinshun', 'Xinshun', '3', 3, 'Xinshun'),
       (375, 'Yamaha', 'Yamaha', '1', 3, 'Yamaha'),
       (376, 'Yawa', 'Yawa', '2', 3, 'Yawa'),
       (377, 'Yiben', 'Yiben', '3', 3, 'Yiben'),
       (378, 'Yuki', 'Yuki', '4', 3, 'Yuki'),
       (379, 'Znen', 'Znen', '1', 3, 'Znen'),
       (380, 'Zongshen', 'Zongshen', '2', 3, 'Zongshen');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (381, 'iO Scooter', 'iO Scooter', '3', 3, 'iO Scooter'),
       (382, 'Восход', 'Восход', '1', 3, 'Восход'),
       (383, 'Вятка', 'Вятка', '2', 3, 'Вятка'),
       (384, 'Днепр', 'Днепр', '1', 3, 'Днепр'),
       (385, 'Други', 'Други', '2', 3, 'Други'),
       (386, 'Дунавия', 'Дунавия', '3', 3, 'Дунавия'),
       (387, 'Иж', 'Иж', '1', 3, 'Иж'),
       (388, 'Карпати', 'Карпати', '1', 3, 'Карпати'),
       (389, 'Ковровец', 'Ковровец', '2', 3, 'Ковровец'),
       (390, 'Мини Мотоциклети', 'Мини Мотоциклети', '1', 3, 'Мини Мотоциклети');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (391, 'Минск', 'Минск', '2', 3, 'Минск'),
       (392, 'Поръчкови', 'Поръчкови', '1', 3, 'Поръчкови'),
       (393, 'Рига', 'Рига', '1', 3, 'Рига'),
       (394, 'ТМЗ', 'ТМЗ', '1', 3, 'ТМЗ'),
       (395, 'Урал', 'Урал', '1', 3, 'Урал'),
       (397, 'Adria', 'Adria', '2', 4, 'Adria'),
       (398, 'Ahorn', 'Ahorn', '3', 4, 'Ahorn'),
       (399, 'Alcar', 'Alcar', '4', 4, 'Alcar'),
       (400, 'Alpha', 'Alpha', '5', 4, 'Alpha'),
       (401, 'Alpine', 'Alpine', '6', 4, 'Alpine');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (402, 'Arca', 'Arca', '7', 4, 'Arca'),
       (403, 'Autoroller', 'Autoroller', '8', 4, 'Autoroller'),
       (404, 'Autostar', 'Autostar', '9', 4, 'Autostar'),
       (405, 'Avento', 'Avento', '10', 4, 'Avento'),
       (406, 'Avondale', 'Avondale', '11', 4, 'Avondale'),
       (407, 'Award', 'Award', '12', 4, 'Award'),
       (408, 'Bavaria-Camp', 'Bavaria-Camp', '1', 4, 'Bavaria-Camp'),
       (409, 'Bawemo', 'Bawemo', '2', 4, 'Bawemo'),
       (410, 'Benimar', 'Benimar', '3', 4, 'Benimar'),
       (411, 'Bergland', 'Bergland', '4', 4, 'Bergland');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (412, 'Beyerland', 'Beyerland', '5', 4, 'Beyerland'),
       (413, 'Bimobil', 'Bimobil', '6', 4, 'Bimobil'),
       (414, 'Burow', 'Burow', '7', 4, 'Burow'),
       (415, 'Bursner', 'Bursner', '8', 4, 'Bursner'),
       (416, 'Burstner', 'Burstner', '9', 4, 'Burstner'),
       (417, 'CA-MO-CAR', 'CA-MO-CAR', '1', 4, 'CA-MO-CAR'),
       (418, 'Carado', 'Carado', '2', 4, 'Carado'),
       (419, 'Caravelair', 'Caravelair', '3', 4, 'Caravelair'),
       (420, 'Caro', 'Caro', '4', 4, 'Caro'),
       (421, 'Cathago', 'Cathago', '5', 4, 'Cathago');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (422, 'Challenger', 'Challenger', '6', 4, 'Challenger'),
       (423, 'Chateau', 'Chateau', '7', 4, 'Chateau'),
       (424, 'Chausson', 'Chausson', '8', 4, 'Chausson'),
       (425, 'CI Interantional', 'CI Interantional', '9', 4, 'CI Interantional'),
       (426, 'Citroen', 'Citroen', '10', 4, 'Citroen'),
       (427, 'Coachmen', 'Coachmen', '11', 4, 'Coachmen'),
       (428, 'Concorde', 'Concorde', '12', 4, 'Concorde'),
       (429, 'Cristall', 'Cristall', '13', 4, 'Cristall'),
       (430, 'CS Reisemobile', 'CS Reisemobile', '14', 4, 'CS Reisemobile'),
       (431, 'Daystar', 'Daystar', '1', 4, 'Daystar');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (432, 'Dehler', 'Dehler', '2', 4, 'Dehler'),
       (433, 'Delta', 'Delta', '3', 4, 'Delta'),
       (434, 'Dethleffs', 'Dethleffs', '4', 4, 'Dethleffs'),
       (435, 'Due Erre', 'Due Erre', '5', 4, 'Due Erre'),
       (436, 'Eifelland', 'Eifelland', '1', 4, 'Eifelland'),
       (437, 'Elnagh', 'Elnagh', '2', 4, 'Elnagh'),
       (438, 'Eriba', 'Eriba', '3', 4, 'Eriba'),
       (439, 'Esterel', 'Esterel', '4', 4, 'Esterel'),
       (440, 'Euramobil', 'Euramobil', '5', 4, 'Euramobil'),
       (441, 'Euro Liner', 'Euro Liner', '6', 4, 'Euro Liner');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (442, 'EVM', 'EVM', '7', 4, 'EVM'),
       (443, 'Fendt', 'Fendt', '1', 4, 'Fendt'),
       (444, 'FFB-Tabbert', 'FFB-Tabbert', '2', 4, 'FFB-Tabbert'),
       (445, 'Fiat', 'Fiat', '3', 4, 'Fiat'),
       (446, 'Fleetwood', 'Fleetwood', '4', 4, 'Fleetwood'),
       (447, 'Ford', 'Ford', '5', 4, 'Ford'),
       (448, 'FR-Mobile', 'FR-Mobile', '6', 4, 'FR-Mobile'),
       (449, 'Frankia', 'Frankia', '7', 4, 'Frankia'),
       (450, 'Granduca', 'Granduca', '1', 4, 'Granduca'),
       (451, 'Hehn', 'Hehn', '1', 4, 'Hehn');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (452, 'Heku', 'Heku', '2', 4, 'Heku'),
       (453, 'Hobby', 'Hobby', '3', 4, 'Hobby'),
       (454, 'Holiday Rambler', 'Holiday Rambler', '4', 4, 'Holiday Rambler'),
       (455, 'Hymer', 'Hymer', '5', 4, 'Hymer'),
       (456, 'Iveco', 'Iveco', '1', 4, 'Iveco'),
       (457, 'JOINT', 'JOINT', '1', 4, 'JOINT'),
       (458, 'Karmann', 'Karmann', '1', 4, 'Karmann'),
       (459, 'Keystone', 'Keystone', '2', 4, 'Keystone'),
       (460, 'Kip', 'Kip', '3', 4, 'Kip'),
       (461, 'Knaus', 'Knaus', '4', 4, 'Knaus');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (462, 'La Strada', 'La Strada', '1', 4, 'La Strada'),
       (463, 'Laika', 'Laika', '2', 4, 'Laika'),
       (464, 'LMC', 'LMC', '3', 4, 'LMC'),
       (465, 'Lunar', 'Lunar', '4', 4, 'Lunar'),
       (466, 'M+ M Mobile', 'M+ M Mobile', '1', 4, 'M+ M Mobile'),
       (467, 'McLouis', 'McLouis', '2', 4, 'McLouis'),
       (468, 'Mercedes-Benz', 'Mercedes-Benz', '3', 4, 'Mercedes-Benz'),
       (469, 'Mirage', 'Mirage', '4', 4, 'Mirage'),
       (470, 'Mobilvetta', 'Mobilvetta', '5', 4, 'Mobilvetta'),
       (471, 'Monaco', 'Monaco', '6', 4, 'Monaco');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (472, 'Moncayo', 'Moncayo', '7', 4, 'Moncayo'),
       (473, 'Movera', 'Movera', '8', 4, 'Movera'),
       (474, 'Munsterland', 'Munsterland', '9', 4, 'Munsterland'),
       (475, 'Niesmann+Bischoff', 'Niesmann+Bischoff', '1', 4, 'Niesmann+Bischoff'),
       (476, 'Nordstar', 'Nordstar', '2', 4, 'Nordstar'),
       (477, 'Ormocar', 'Ormocar', '1', 4, 'Ormocar'),
       (478, 'Peugeot', 'Peugeot', '1', 4, 'Peugeot'),
       (479, 'Phoenix', 'Phoenix', '2', 4, 'Phoenix'),
       (480, 'Pilote', 'Pilote', '3', 4, 'Pilote'),
       (481, 'Possl', 'Possl', '4', 4, 'Possl');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (482, 'Rapido', 'Rapido', '1', 4, 'Rapido'),
       (483, 'Reimo', 'Reimo', '2', 4, 'Reimo'),
       (484, 'Reisemobile Beier', 'Reisemobile Beier', '3', 4, 'Reisemobile Beier'),
       (485, 'Rimor', 'Rimor', '4', 4, 'Rimor'),
       (486, 'Riva', 'Riva', '5', 4, 'Riva'),
       (487, 'Riviera', 'Riviera', '6', 4, 'Riviera'),
       (488, 'RMB', 'RMB', '7', 4, 'RMB'),
       (489, 'Roadtrek', 'Roadtrek', '8', 4, 'Roadtrek'),
       (490, 'Robel-Mobil', 'Robel-Mobil', '9', 4, 'Robel-Mobil'),
       (491, 'Rockwood', 'Rockwood', '10', 4, 'Rockwood');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (492, 'Scarnia', 'Scarnia', '1', 4, 'Scarnia'),
       (493, 'Sea', 'Sea', '2', 4, 'Sea'),
       (494, 'Selbstbau', 'Selbstbau', '3', 4, 'Selbstbau'),
       (495, 'Shato', 'Shato', '4', 4, 'Shato'),
       (496, 'SLOOP', 'SLOOP', '5', 4, 'SLOOP'),
       (497, 'Sprite', 'Sprite', '6', 4, 'Sprite'),
       (498, 'Sterckeman', 'Sterckeman', '7', 4, 'Sterckeman'),
       (499, 'Subaru', 'Subaru', '8', 4, 'Subaru'),
       (500, 'SUNLIGHT', 'SUNLIGHT', '9', 4, 'SUNLIGHT'),
       (501, 'Sunroller', 'Sunroller', '10', 4, 'Sunroller');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (502, 'Tabbert', 'Tabbert', '1', 4, 'Tabbert'),
       (503, 'TEC', 'TEC', '2', 4, 'TEC'),
       (504, 'Tischer', 'Tischer', '3', 4, 'Tischer'),
       (505, 'Triple E', 'Triple E', '4', 4, 'Triple E'),
       (506, 'Vario', 'Vario', '1', 4, 'Vario'),
       (507, 'Vitesse', 'Vitesse', '2', 4, 'Vitesse'),
       (508, 'VW', 'VW', '3', 4, 'VW'),
       (509, 'Weinsberg', 'Weinsberg', '1', 4, 'Weinsberg'),
       (510, 'Weippert', 'Weippert', '2', 4, 'Weippert'),
       (511, 'Westfalia', 'Westfalia', '3', 4, 'Westfalia');
INSERT INTO db.brands (id, name, slug, `order`, section_id, seo_title)
VALUES (512, 'Wilk', 'Wilk', '4', 4, 'Wilk'),
       (513, 'Winnebago', 'Winnebago', '5', 4, 'Winnebago'),
       (514, 'Woelcke', 'Woelcke', '6', 4, 'Woelcke');